on:
  push:
    branches: [main, dev]
  pull_request:

name: Test C/C++ examples

jobs:
  test_ffi_examples:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        rust:
          - stable

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.12
        with:
          cmake-version: '3.16.x'
      - uses: Swatinem/rust-cache@v1
      - name: Run cmake
        run: |
            cmake -Sc_example -Bbuild
      - name: Build
        run: |
            cmake --build build
      - name: Run C example
        run: |
          ./build/example
